change troubleshoot.io to troubleshoot.sh
replicatedhq/troubleshoot pull request #1075
Opened 2023-03-23 20:44 UTC by grantmiller

## Description, Motivation and Context

i don't believe that troubleshoot.io is right... should be troubleshoot.sh

2023-03-23 20:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/replicatedhq/troubleshoot?pullRequest=1075) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/replicatedhq/troubleshoot?pullRequest=1075) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/replicatedhq/troubleshoot?pullRequest=1075) it.</sub>

2023-03-23 21:51 UTC, chris-sanders commented
I believe this relates to #1070 which we need to fix, but this just fixes the documentation string we need to also adjust the default search, yes?

2023-03-24 03:09 UTC, xavpaice commented
There's a number of changes that need to happen at the same time: see [this query](https://github.com/search?q=org%3Areplicatedhq+troubleshoot.io&type=code)

tl;dr:
* This change in Troubleshoot plus a rebuild of the schemas and docs
* search/replace in KOTS and kURL
* https://github.com/replicatedhq/troubleshoot.sh/pull/480 (docs)

2023-03-24 03:36 UTC, xavpaice commented
https://github.com/replicatedhq/kots/pull/3763

2023-03-24 03:41 UTC, xavpaice commented
https://github.com/replicatedhq/kURL/pull/4247

2023-03-24 09:38 UTC, danj-replicated commented
rather than treat this as a co-ordinated change, would it be better to address this in a similar way to how kubernetes treats label deprecations?

i.e: we add the new label while leaving the original one in place and set a deprecation date that upstream dependants (kurl) must meet?

2023-03-24 11:30 UTC, banjoh commented
> rather than treat this as a co-ordinated change, would it be better to address this in a similar way to how kubernetes treats label deprecations?
> 
> i.e: we add the new label while leaving the original one in place and set a deprecation/removal date that upstream dependants (kurl) must meet?

My thoughts exactly.

In addition, since we (Replicated) maintain KOTS & kurl, we can make the changes there to deprecate the label. In KOTS side, we would need to update existing labels when users upgrade their KOTS deployments.

2023-03-25 03:31 UTC, xavpaice commented
I think if we're going to deprecate a label we need to work in this order:
* deprecate in Troubleshoot, search for both new and old for a time
* Adjust all the docs
* in KOTs, search for new and old.  Change what we store to the new label.
* In kURL, just change what we store to the new label.

Sound reasonable?

2023-03-27 10:39 UTC, danj-replicated commented
yeh sounds like a plan

2023-03-27 11:21 UTC, banjoh commented
Yep, that sounds like a good plan

2023-03-27 11:27 UTC, banjoh commented
> In kURL, just change what we store to the new label.

There will be a small window where new add-ons installed using an old kURL installer won't work. It might be something we can have checked in [flannel's preflight](https://github.com/replicatedhq/kURL/blob/main/addons/flannel/0.21.3/host-preflight.yaml) (kurl-version > v2023.XX.XX) since its the only reference I see the label being used.

2023-04-12 06:09 UTC, xavpaice requested changes

2023-04-12 06:09 UTC, xavpaice commented on docs/preflight.md
> +      --cache-dir string               Default cache directory (default "/Users/xavpaice/.kube/cache")
```suggestion
      --cache-dir string               Default cache directory (default "$HOME/.kube/cache")
```

2023-04-12 06:09 UTC, xavpaice commented on cmd/troubleshoot/cli/root.go
> +	cmd.Flags().StringSliceP("selector", "l", []string{"troubleshoot.sh/kind=support-bundle"}, "selector to filter on for loading additional support bundle specs found in secrets within the cluster")
if we're going to deprecate troubleshoot.io, but keep support for it, what should we have as the default here?  I think the new, but want feedback on that given that we want to support the old and the new label.  For one to be default, that means that folks using the other will need to supply it on the CLI, unless we add logic for multiple labels and have this default to both labels.

2023-04-12 06:09 UTC, xavpaice commented on docs/support-bundle.md
> +      --cache-dir string               Default cache directory (default "/Users/xavpaice/.kube/cache")
```suggestion
      --cache-dir string               Default cache directory (default "$HOME/.kube/cache")
```

2023-04-12 06:09 UTC, xavpaice commented on docs/support-bundle.md
> +  -l, --selector strings               selector to filter on for loading additional support bundle specs found in secrets within the cluster (default [troubleshoot.sh/kind=support-bundle])
as above, need to determine the correct default

2023-06-12 02:05 UTC, xavpaice commented
this has been replaced by #1203

2023-06-12 02:05 UTC, closed without merging