feat(analyzer): add certificate analyzer
replicatedhq/troubleshoot pull request #1128
Opened 2023-04-18 06:06 UTC by DexterYan

## Description, Motivation and Context

Please include a summary of the change or what problem it solves. Please also include relevant motivation and context.

issue: #762

# Support Bundle Yaml
```
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: default
spec:
  collectors:
    - certificates: 
        secrets:
            - name: envoycert
              namespaces:
                - kube-system
                - projectcontour
        configMaps:
            - name: kube-root-ca.crt
              namespaces:
                - curlie
                - kurl
  analyzers:
    - certificates: # Iterate through list of certificates
        outcomes:
          - pass:
              message: "certificate is valid"
          - warn:
              when: "notAfter < Today + 15 days"
              message: "certificate is about to expire"
          - fail:
              when: "notAfter < Today"
              message: "certificate has expired"
```

# Result Json
```
{
    "analyzerResults": [
        {
            "name": "cerfiticates.verification",
            "labels": {
                "desiredPosition": "1",
                "iconKey": "",
                "iconUri": ""
            },
            "insight": {
                "name": "cerfiticates.verification",
                "labels": {
                    "iconKey": "",
                    "iconUri": ""
                },
                "primary": "Cerfiticates Verification",
                "detail": "ca.crt certificate is valid from envoycert secret of projectcontour",
                "severity": "debug"
            },
            "severity": "debug",
            "analyzerSpec": ""
        },
        {
            "name": "cerfiticates.verification",
            "labels": {
                "desiredPosition": "1",
                "iconKey": "",
                "iconUri": ""
            },
            "insight": {
                "name": "cerfiticates.verification",
                "labels": {
                    "iconKey": "",
                    "iconUri": ""
                },
                "primary": "Cerfiticates Verification",
                "detail": "ca.crt certificate is about to expire in 15 days from envoycert secret of projectcontour ",
                "severity": "warn"
            },
            "severity": "warn",
            "analyzerSpec": ""
        },
        {
            "name": "cerfiticates.verification",
            "labels": {
                "desiredPosition": "1",
                "iconKey": "",
                "iconUri": ""
            },
            "insight": {
                "name": "cerfiticates.verification",
                "labels": {
                    "iconKey": "",
                    "iconUri": ""
                },
                "primary": "Cerfiticates Verification",
                "detail": "tls.crt certificate is valid from envoycert secret of projectcontour",
                "severity": "debug"
            },
            "severity": "debug",
            "analyzerSpec": ""
        },
        {
            "name": "cerfiticates.verification",
            "labels": {
                "desiredPosition": "1",
                "iconKey": "",
                "iconUri": ""
            },
            "insight": {
                "name": "cerfiticates.verification",
                "labels": {
                    "iconKey": "",
                    "iconUri": ""
                },
                "primary": "Cerfiticates Verification",
                "detail": "tls.crt certificate is about to expire in 15 days from envoycert secret of projectcontour ",
                "severity": "warn"
            },
            "severity": "warn",
            "analyzerSpec": ""
        },
        {
            "name": "cerfiticates.verification",
            "labels": {
                "desiredPosition": "1",
                "iconKey": "",
                "iconUri": ""
            },
            "insight": {
                "name": "cerfiticates.verification",
                "labels": {
                    "iconKey": "",
                    "iconUri": ""
                },
                "primary": "Cerfiticates Verification",
                "detail": "ca.crt certificate is valid from kube-root-ca.crt configmap of kurl",
                "severity": "debug"
            },
            "severity": "debug",
            "analyzerSpec": ""
        },
        {
            "name": "cerfiticates.verification",
            "labels": {
                "desiredPosition": "1",
                "iconKey": "",
                "iconUri": ""
            },
            "insight": {
                "name": "cerfiticates.verification",
                "labels": {
                    "iconKey": "",
                    "iconUri": ""
                },
                "primary": "Cerfiticates Verification",
                "detail": "ca.crt certificate is about to expire in 15 days from kube-root-ca.crt configmap of kurl ",
                "severity": "warn"
            },
            "severity": "warn",
            "analyzerSpec": ""
        }
    ],
}
```

## Checklist

- [ ] New and existing tests pass locally with introduced changes.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] The commit message(s) are informative and highlight any breaking changes
- [ ] Any documentation required has been added/updated. For changes to https://troubleshoot.sh/ create a PR [here](https://github.com/replicatedhq/troubleshoot.sh/pulls)

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

2023-05-28 22:41 UTC, CpuID requested changes
overall LGTM, haven't tested it locally but the tests exist and are passing according to GitHub :)

just a few spelling fixes to apply 👍

2023-05-28 22:41 UTC, CpuID commented on pkg/analyze/certificates.go
> +		return "Cerfiticates Verification"
```suggestion
		return "Certificates Verification"
```

2023-05-28 22:41 UTC, CpuID commented on pkg/analyze/certificates_test.go
> +					Title:   "Cerfiticates Verification",
```suggestion
					Title:   "Certificates Verification",
```

2023-05-28 22:41 UTC, CpuID commented on pkg/analyze/certificates_test.go
> +					Title:   "Cerfiticates Verification",
```suggestion
					Title:   "Certificates Verification",
```

2023-05-28 22:41 UTC, CpuID commented on pkg/analyze/certificates_test.go
> +					Title:   "Cerfiticates Verification",
```suggestion
					Title:   "Certificates Verification",
```

2023-05-28 22:41 UTC, CpuID commented on pkg/analyze/certificates.go
> +func (a *AnalyzeCertificates) analyzeAnalyzeCertificatesResult(certifcates []collect.CertCollection, outcomes []*troubleshootv1beta2.Outcome) ([]*AnalyzeResult, error) {
```suggestion
func (a *AnalyzeCertificates) analyzeAnalyzeCertificatesResult(certificates []collect.CertCollection, outcomes []*troubleshootv1beta2.Outcome) ([]*AnalyzeResult, error) {
```

2023-05-28 22:41 UTC, CpuID commented on pkg/analyze/certificates.go
> +	for _, cert := range certifcates {
```suggestion
	for _, cert := range certificates {
```

2023-05-29 00:18 UTC, CpuID approved these changes

2023-05-29 03:30 UTC, xavpaice approved these changes, later dismissed

2023-05-29 04:39 UTC, xavpaice approved these changes

2023-05-29 04:40 UTC, merged