fix(collector): wait until run pod has been deleted
replicatedhq/troubleshoot pull request #1194
Opened 2023-05-30 00:53 UTC by DexterYan

## Description, Motivation and Context

- Make sure the run pod has been deleted before the troubleshoot.sh finished running
- Poll every second to check if the Pod has been deleted. The maximum grace period is 2 Minutes.

Fixes: #1186

## Checklist

- [ ] New and existing tests pass locally with introduced changes.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] The commit message(s) are informative and highlight any breaking changes
- [ ] Any documentation required has been added/updated. For changes to https://troubleshoot.sh/ create a PR [here](https://github.com/replicatedhq/troubleshoot.sh/pulls)

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

2023-05-30 00:54 UTC, DexterYan commented
## Example Support Bundle
```
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: example
spec:
  collectors:
    - runPod:
        collectorName: "my-counter"
        timeout: 5s
        podSpec:
          containers:
          - name: my-counter
            image: ubuntu
            command: ["/bin/bash", "-c", 'for i in {1..30}; do echo "count $i"; sleep 1; done']
```

## Output
```
./bin/support-bundle test2.yaml -v0                                

 * failed to run collector: run-pod/my-counter: timeout
 Collecting support bundle ⠇ cluster-resources
support-bundle-2023-05-30T12_49_53.tar.gz

============ Collectors summary =============
Suceeded (S), eXcluded (X), Failed (F)
=============================================
run-pod/my-counter (F) : 34,059ms
cluster-resources (S)  : 1,877ms
cluster-info (S)       : 5ms

============ Redactors summary =============
In-cluster collectors : 375ms

============= Analyzers summary =============
Suceeded (S), eXcluded (X), Failed (F)
=============================================
No analyzers executed

Duration: 36,339ms
```

2023-05-30 00:59 UTC, DexterYan commented
## Example Preflight
```
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: sample
spec:
  collectors:
    - run:
        collectorName: "static-hi"
        image: "alpine:3"
        command: ["echo", "hi static!"]
  analyzers:
    - textAnalyze:
        checkName: Said hi!
        fileName: /static-hi.log
        regex: "hi static"
        outcomes:
          - fail:
              message: Didn't say hi.
          - pass:
              message: Said hi!

```

## output
```
./bin/preflight test3.yaml -v0

============ Collectors summary =============
Suceeded (S), eXcluded (X), Failed (F)
=============================================
run/static-hi (S)     : 4,095ms
cluster-resources (S) : 1,877ms
cluster-info (S)      : 1ms

============ Redactors summary =============
No redactors executed

============= Analyzers summary =============
Suceeded (S), eXcluded (X), Failed (F)
=============================================
Said hi! (S) : 0ms

Duration: 7,779ms
```

2023-05-30 01:04 UTC, DexterYan commented
## Previous Failed Support Bundle
```
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: example
spec:
  collectors:
    - runPod:
        collectorName: "my-counter"
        timeout: 5s
        podSpec:
          containers:
            - name: my-counter
              image: ubuntu
              command:
                [
                  "/bin/bash",
                  "-c",
                  'for i in {1..2}; do echo "count $i"; sleep 1; done',
                ]
    - runPod:
        collectorName: "my-counter"
        timeout: 5s
        podSpec:
          containers:
            - name: my-counter
              image: ubuntu
              command:
                [
                  "/bin/bash",
                  "-c",
                  'for i in {1..2}; do echo "count again $i"; sleep 1; done',
                ]

```
## Output
```
./bin/support-bundle test4.yaml -v0

 * failed to run collector: run-pod/my-counter: timeout
 * failed to run collector: run-pod/my-counter: timeout
 Collecting support bundle ⠏ cluster-info
support-bundle-2023-05-30T13_01_54.tar.gz

============ Collectors summary =============
Suceeded (S), eXcluded (X), Failed (F)
=============================================
run-pod/my-counter (F) : 7,044ms
cluster-resources (S)  : 1,875ms
cluster-info (S)       : 6ms

============ Redactors summary =============
In-cluster collectors : 386ms

============= Analyzers summary =============
Suceeded (S), eXcluded (X), Failed (F)
=============================================
No analyzers executed

Duration: 16,387ms
```

2023-05-30 01:16 UTC, CpuID approved these changes

2023-05-31 14:08 UTC, banjoh requested changes
Please add logs (`klog.V(2)`) to show progress. This will come in handy whenever troubleshooting to see what the collector is doing. I suggest logging at least the following.
* Pod <name> has been created in namespace ...
* .... created in namespace with a timeout of <num>
* Pod <name> has been scheduled for deletion
* Polling pod <name> for deletion

The log lines can be whatever you see best.

2023-05-31 14:08 UTC, banjoh commented on pkg/collect/run_pod.go
> +		const gracePeriodMinutes = 2 * time.Minute
Please create constant in `constants.go`

2023-05-31 14:08 UTC, banjoh commented on pkg/collect/run_pod.go
> +		// Wait until the pod is deleted
Log here to let the user know that we are deleting the pod.

2023-05-31 14:18 UTC, banjoh commented
Overall, the approach you have here is good.

We would need to update [the documentation](https://troubleshoot.sh/docs/collect/run-pod/) to reflect this new changes. We also need to correct [the timeout](https://troubleshoot.sh/docs/collect/run-pod/#timeout-optional) documentation to reflect this change. Its not `30s` max, rather its `2mins + timeout` at the worst case, and if the parameter is not defined, the pod can potentially run forever.

2023-06-01 04:08 UTC, DexterYan commented
Hey @banjoh 
Thank you for reviewing my PR. I have changed my pr based on your advice. And I think your first suggestion about using force pod deletion is necessary for solving issue #1188 

I have created another PR to reflect those changes 
#1196

2023-06-01 04:43 UTC, closed without merging