make ConfigMap collector namespace-optional
replicatedhq/troubleshoot pull request #1212
Opened 2023-06-06 14:26 UTC by adamancini

## Description, Motivation and Context

When no namespace is given in the ConfigMaps collector spec, use the namespace from the current kubectl context.

Fixes: #907 

## Checklist

- [x] New and existing tests pass locally with introduced changes.
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] The commit message(s) are informative and highlight any breaking changes
- [x] Any documentation required has been added/updated. For changes to https://troubleshoot.sh/ create a PR [here](https://github.com/replicatedhq/troubleshoot.sh/pulls)

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

2023-06-06 14:36 UTC, adamancini commented
Using the test spec from my PR:

```
tail support-bundle-2023-06-06T10_09_37/configmaps/* support-bundle-2023-06-06T10_09_37/configmaps-errors/* 
==> support-bundle-2023-06-06T10_09_37/configmaps/cluster-info.json <==
{
  "namespace": "",
  "name": "cluster-info",
  "key": "",
  "configMapExists": false,
  "keyExists": false,
  "data": null
}
==> support-bundle-2023-06-06T10_09_37/configmaps/does-not-exist.json <==
{
  "namespace": "",
  "name": "does-not-exist",
  "key": "",
  "configMapExists": false,
  "keyExists": false,
  "data": null
}
==> support-bundle-2023-06-06T10_09_37/configmaps/kube-proxy.json <==
{
  "namespace": "",
  "name": "kube-proxy",
  "key": "",
  "configMapExists": true,
  "keyExists": false,
  "data": null
}
==> support-bundle-2023-06-06T10_09_37/configmaps/kube-root-ca.crt.json <==
{
  "namespace": "",
  "name": "kube-root-ca.crt",
  "key": "",
  "configMapExists": true,
  "keyExists": false,
  "data": null
}
==> support-bundle-2023-06-06T10_09_37/configmaps/kube-system <==

==> support-bundle-2023-06-06T10_09_37/configmaps-errors/cluster-info.json <==
[
  "configmaps \"cluster-info\" not found"
]
==> support-bundle-2023-06-06T10_09_37/configmaps-errors/does-not-exist.json <==
[
  "configmaps \"does-not-exist\" not found"
]%                                                                                                   
```

2023-06-06 20:30 UTC, diamonwiggins approved these changes
Approved with a suggestion, and a caveat of there has been some discussion recently if we should ever use the `kubeconfig` context's namespace at all. Not sure what the argument is there, but i don't object to this change.

2023-06-06 20:30 UTC, diamonwiggins commented on pkg/collect/configmap.go
> +			klog.V(2).Infof("no namespace was set for configmap '%s': using namespace '%s' from current kubectl context", c.Collector.Name, ns)
```suggestion
			klog.V(2).Infof("no namespace was set for configmap '%s': using namespace '%s' from current kubeconfig context", c.Collector.Name, ns)
```

2023-06-06 20:30 UTC, diamonwiggins submitted a review, later dismissed
Approved with a suggestion, and a caveat of there has been some discussion recently if we should ever use the `kubeconfig` context's namespace at all. Not sure what the argument is there, but i don't object to this change.

2023-06-12 20:07 UTC, diamonwiggins approved these changes

2023-06-13 11:26 UTC, banjoh requested changes

2023-06-13 11:26 UTC, banjoh commented on pkg/collect/configmap.go
> +		klog.V(1).Infof("looking for configmap '%s' in namespace '%s'", c.Collector.Name, namespace)
Within the collectors, this needs to be `klog.V(2)` as per [this "very easy to find" documentation](https://github.com/replicatedhq/troubleshoot/blob/a5628874b08c76a8544dfba6da62c7605118d91f/pkg/logger/logger.go#L4)

Note to self: I really need to extract this into our [dev guide documentation](https://github.com/replicatedhq/troubleshoot/issues/1031)

2023-06-13 11:35 UTC, banjoh approved these changes

2023-06-13 17:12 UTC, merged