WIP fix(json_compare): solve unorderd slice deep equal
replicatedhq/troubleshoot pull request #1300
Opened 2023-08-16 06:27 UTC by DexterYan

## Description, Motivation and Context

- add deepEqualWithSlicesOrderingIgnored 

Fixes: #1274
## Checklist

- [ ] New and existing tests pass locally with introduced changes.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] The commit message(s) are informative and highlight any breaking changes
- [ ] Any documentation required has been added/updated. For changes to https://troubleshoot.sh/ create a PR [here](https://github.com/replicatedhq/troubleshoot.sh/pulls)

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

2023-08-21 13:02 UTC, danj-replicated requested changes

2023-08-21 13:02 UTC, danj-replicated commented on pkg/analyze/json_compare.go
> +
I know this is a fairly simple function but it's name is a little confusing. can we get a brief description here to help any future readers grok what's happening.

2023-08-21 23:22 UTC, DexterYan commented on pkg/analyze/json_compare.go
> +
Thank you @danj-replicated. Good idea! I have updated the pr to make it more readable and a description for a better understanding.

2023-08-24 09:28 UTC, danj-replicated approved these changes

2023-08-24 10:48 UTC, banjoh approved these changes

2023-08-24 10:48 UTC, merged