Local watch script
replicatedhq/troubleshoot pull request #1304
Opened 2023-08-21 21:19 UTC by adamancini

## Description, Motivation and Context

build automatically on save

## Checklist

- [x] New and existing tests pass locally with introduced changes.
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] The commit message(s) are informative and highlight any breaking changes
- [x] Any documentation required has been added/updated. For changes to https://troubleshoot.sh/ create a PR [here](https://github.com/replicatedhq/troubleshoot.sh/pulls)

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

2023-08-21 21:26 UTC, DexterYan approved these changes

2023-08-24 08:55 UTC, banjoh requested changes
How does this script differ from https://github.com/replicatedhq/troubleshoot/blob/main/bin/watchrsync.js?

2023-08-24 08:56 UTC, banjoh commented
> How does this script differ from https://github.com/replicatedhq/troubleshoot/blob/main/bin/watchrsync.js?

Ah, got it. One does not rsync, the other does.

2023-08-24 08:58 UTC, banjoh approved these changes

2023-08-24 08:58 UTC, banjoh commented on bin/watch.js
> +    command: 'make',
You can try `make build`. It should take the same amount of time. It builds all binaries in parallel.

2023-08-25 03:12 UTC, merged