fix(support-bundle): default in-cluster collectors in host support bundle
replicatedhq/troubleshoot pull request #1394
Opened 2023-11-23 18:45 UTC by banjoh

## Description, Motivation and Context

Ensure cluster-resources and cluster-info collectors are present only when a support bundle spec contains in-cluster collectors.

Fixes: #1393 

## Checklist

- [ ] New and existing tests pass locally with introduced changes.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] The commit message(s) are informative and highlight any breaking changes
- [ ] Any documentation required has been added/updated. For changes to https://troubleshoot.sh/ create a PR [here](https://github.com/replicatedhq/troubleshoot.sh/pulls)

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

2023-11-23 19:52 UTC, xavpaice approved these changes

2023-11-23 20:20 UTC, xavpaice requested changes
not sure why this is failing tests, but it is?

2023-11-24 17:25 UTC, banjoh commented
> not sure why this is failing tests, but it is?

Its a valid issue. I've fixed it in [this commit](https://github.com/replicatedhq/troubleshoot/pull/1394/commits/799c55a15a2f9b8a9a068e9c81fb2db669a0a692). Essentially, a bug surfaced itself when collecting a support bundle using a spec like below

```yaml
apiVersion: troubleshoot.sh/v1beta2
kind: Collector
metadata:
  name: collector-sample
spec:
  collectors: []
```

[Golang treats empty slices the same as nil slices when it comes to its built in functions](https://freshman.tech/snippets/go/nil-vs-empty-slices/) such as `append()`, `len()` etc. That last commit handles that peculiar behaviour.

2023-11-27 10:27 UTC, banjoh commented
@xavpaice tests have been fixed

2023-11-27 12:06 UTC, danj-replicated approved these changes

2023-11-27 17:19 UTC, diamonwiggins approved these changes

2023-11-27 18:17 UTC, xavpaice approved these changes

2023-11-27 18:33 UTC, merged