feat: [ISSUE-1401]: Added helm get values option in Helm collector
replicatedhq/troubleshoot pull request #1402
Opened 2023-12-16 03:10 UTC by avaakash

## Description, Motivation and Context

Please include a summary of the change or what problem it solves. Please also include relevant motivation and context.

## Checklist

- [ ] New and existing tests pass locally with introduced changes.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] The commit message(s) are informative and highlight any breaking changes
- [ ] Any documentation required has been added/updated. For changes to https://troubleshoot.sh/ create a PR [here](https://github.com/replicatedhq/troubleshoot.sh/pulls)

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

2023-12-16 03:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/replicatedhq/troubleshoot?pullRequest=1402) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/replicatedhq/troubleshoot?pullRequest=1402) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/replicatedhq/troubleshoot?pullRequest=1402) it.</sub>

2023-12-19 20:01 UTC, banjoh requested changes
The overall change looks good to me. I have added some comments, mostly around cleanup and some improvements I noticed that need to be done

The other missing bit that would be needed in this PR is
- Documenting the [helm collector](https://troubleshoot.sh/docs/collect/helm/) in [this file](https://github.com/replicatedhq/troubleshoot.sh/blob/main/docs/source/collect/helm.md)
- Updating [this e2e test](https://github.com/replicatedhq/troubleshoot/blob/main/test/e2e/support-bundle/helm_collector_e2e_test.go). It will involve adding some values the [helm test fixture](https://github.com/replicatedhq/troubleshoot/tree/main/test/e2e/support-bundle/testdata/charts) and passing in some values which you will assert their existence [here](https://github.com/replicatedhq/troubleshoot/blob/53113c0170ce4d1d02ef7552e5cebdc5ae6d4feb/test/e2e/support-bundle/helm_collector_e2e_test.go#L66-L68)

2023-12-19 20:01 UTC, banjoh commented on pkg/collect/helm.go
> +	getAction.Version = revision
Would `getAction.AllValues = true` be better here so we can get all values rather than the only ones provided by the user?

2023-12-19 20:01 UTC, banjoh commented on pkg/collect/helm.go
> +	helmValues, _ := getAction.Run(releaseName)
Please return this error so it can be stored in the support bundle

2023-12-19 20:01 UTC, banjoh commented on pkg/collect/helm.go
>  		return nil, errors.Wrap(err, "failed to get Helm release history")
I know this is not part of this PR, but can we store this error in the support bundle like we do [other collectors](https://github.com/replicatedhq/troubleshoot/blob/53113c0170ce4d1d02ef7552e5cebdc5ae6d4feb/pkg/collect/exec.go#L98)? This would be stored in `helm/errors.json`

Also, using klog, please log this error i.e `klog.Error(...)`

Please remove `log.Fatalf("Failed to list Helm releases: %v", err)` and return the error instead

2023-12-19 20:01 UTC, banjoh commented on pkg/collect/helm.go
>  	history, _ := action.NewHistory(actionConfig).Run(releaseName)
Its not your code, but if you can return this error too, that would be great.

2024-01-08 10:09 UTC, avaakash commented on pkg/collect/helm.go
> +	getAction.Version = revision
Yes that would make sense

2024-01-08 18:09 UTC, banjoh reviewed
Error handling changes look good, thanks for that. I have added one code suggestion to the PR

2024-01-08 18:09 UTC, banjoh commented on pkg/collect/helm.go
> +		return nil, errors.New(string(errs))
Should never happen, but I prefer handling errors whenever possible

```suggestion
		errs, err := json.MarshalIndent(error_list, "", " ")
		if err != nil {
			strs := []string{}
			for _, e := range error_list {
				strs = append(strs, e.Error())
			}
			return nil, errors.New(strings.Join(strs, "\n"))
		}
		return nil, errors.New(string(errs))
```

2024-01-12 19:21 UTC, banjoh commented
Docs PR: https://github.com/replicatedhq/troubleshoot.sh/pull/534

2024-01-12 20:03 UTC, banjoh requested changes
The PR changes work. I added one last comment needing to be changes

2024-01-12 20:03 UTC, banjoh commented on test/e2e/support-bundle/helm_collector_e2e_test.go
> +			assert.Equal(t, []interface{}([]interface{}{map[string]interface{}{"name": "TEST_ENV_VAR", "value": "test-value"}}), results[0].VersionInfo[0].Values["extraEnvVars"])
nit pick: You could add another check to see if the default values are also collected e.g `image.tag == 1.25.2-debian-11-r3`

2024-01-12 20:03 UTC, banjoh commented on pkg/collect/helm.go
> +		return nil, nil
The `error` type does not get marshalled correctly

```suggestion
		errsToMarshal := []string{}
		for _, e := range err {
			errsToMarshal = append(errsToMarshal, e.Error())
		}
		output.SaveResult(c.BundlePath, "helm/errors.json", marshalErrors(errsToMarshal))
		klog.Errorf("error collecting helm release info: %v", err)
		return output, nil
```

2024-01-16 18:25 UTC, banjoh approved these changes
LGTM

2024-01-16 19:12 UTC, merged