feat: make load-cluster-specs the default
replicatedhq/troubleshoot pull request #1602
Opened 2024-08-22 23:20 UTC by diamonwiggins

## Description, Motivation and Context

Please include a summary of the change or what problem it solves. Please also include relevant motivation and context.

## Checklist

- [ ] New and existing tests pass locally with introduced changes.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] The commit message(s) are informative and highlight any breaking changes
- [ ] Any documentation required has been added/updated. For changes to https://troubleshoot.sh/ create a PR [here](https://github.com/replicatedhq/troubleshoot.sh/pulls)

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

2024-08-23 19:10 UTC, hedge-sparrow requested changes
some minor docs typos?

2024-08-23 19:10 UTC, hedge-sparrow commented on docs/preflight.md
> +      --cache-dir string               Default cache directory (default "/Users/diamonwiggins/.kube/cache")
Might want to make this more generic

2024-08-23 19:10 UTC, hedge-sparrow commented on docs/support-bundle.md
> +      --cache-dir string               Default cache directory (default "/Users/diamonwiggins/.kube/cache")
did this get expanded by your editor or something?

2024-08-23 22:39 UTC, hedge-sparrow approved these changes

2024-08-24 08:55 UTC, banjoh approved these changes
A welcome change indeed!

LGTM

2024-08-26 13:54 UTC, merged