feat(analyzer): enable host os info analyzer to support multiple nodes
replicatedhq/troubleshoot pull request #1618
Opened 2024-09-19 20:00 UTC by DexterYan

## Description, Motivation and Context

Please include a summary of the change or what problem it solves. Please also include relevant motivation and context.

## Checklist

- [ ] New and existing tests pass locally with introduced changes.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] The commit message(s) are informative and highlight any breaking changes
- [ ] Any documentation required has been added/updated. For changes to https://troubleshoot.sh/ create a PR [here](https://github.com/replicatedhq/troubleshoot.sh/pulls)

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

2024-09-20 22:28 UTC, nvanthao requested changes
LGTM, only 1 nit suggest

2024-09-20 22:28 UTC, nvanthao commented on pkg/analyze/host_os_info.go
> +		} else {
nit: this else block can be removed.

2024-09-22 03:27 UTC, DexterYan commented on pkg/analyze/host_os_info.go
> +		} else {
removed

2024-09-24 03:56 UTC, xavpaice commented
the main thing to review here is that we have a ..._nodes.json that lists the nodes which were collected, and the analyzer then uses that to find the appropriate files.  We chose this over wildcard as it is more precise, a wildcard could pick up stuff we don't want if we later change the collector to add more files (like raw output).

2024-09-25 03:48 UTC, DexterYan commented
Now the code has been improved to create only one file called `node_list.json` which has all the node name. It can be used for all host collectors without duplicated.

2024-09-25 06:14 UTC, nvanthao approved these changes
LGTM

2024-09-25 22:25 UTC, merged