feat: add support for matchExpressions when filtering for nodes
replicatedhq/troubleshoot pull request #1697
Opened 2024-11-28 15:48 UTC by miguelvr

## Description, Motivation and Context

Includes the ability to use a Kubernetes `matchExpressions` label selector for the `nodeResources` analyzer.

I wanted to write pre-flight checks to analyze nodes that contained a specific label and another that negated it. Currently, this is not possible with the `MatchLabel` selector. It would be possible with a `MatchExpressions` label selector by using the negation operators (e.g., `NotIn` / `DoesNotExist`)

## Checklist

- [x] New and existing tests pass locally with introduced changes.
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] The commit message(s) are informative and highlight any breaking changes
- [ ] Any documentation required has been added/updated. For changes to https://troubleshoot.sh/ create a PR [here](https://github.com/replicatedhq/troubleshoot.sh/pulls)

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

2024-11-28 15:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/replicatedhq/troubleshoot?pullRequest=1697) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/replicatedhq/troubleshoot?pullRequest=1697) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/replicatedhq/troubleshoot?pullRequest=1697) it.</sub>

2024-11-28 21:41 UTC, nvanthao requested changes
Many thanks for the contribution @miguelvr!

The changes look good, I will approve it after we fix the failed Github Action.

When we introduce new field in Troubleshoot spec, we have to ensure the schemas are updated accordingly. Please run below command from the project root directory and commit the changes accordingly.

```bash
make schemas
make check-schemas
```

2024-11-29 13:15 UTC, miguelvr commented
@nvanthao `make generate` fails locally because it assumes a specific relative path directory structure (that I think it's used in CI, based on the git history)

2024-11-30 12:15 UTC, nvanthao approved these changes
Thank you for running the commands and for pointing out the issue with the relative paths. We'll address that separately to ensure smoother local workflows.

Since the schemas were successfully generated by other targets and everything else looks good, I'll go ahead and approve this PR. Many thanks for your contribution!

2024-11-30 12:15 UTC, merged