feat: add support for GPU resources
replicatedhq/troubleshoot pull request #1701
Opened 2024-12-02 11:59 UTC by miguelvr

## Description, Motivation and Context

`nvidia.com/gpu` is a common resource for many AI applications, but currently, Troubleshoot does not allow users to check the availability of GPUs in their cluster. 

I've considered taking a more generic approach with a function `resourceName(<resource>)`, but decided against it because it would either require taking in the units as a parameter `resourceName(<resource>, <units>)` or default to something like `DecimalSI`, which could lead to errors for certain resources.

For simplicity, I decided to with the explicit approach. 

## Checklist

- [x] New and existing tests pass locally with introduced changes.
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] The commit message(s) are informative and highlight any breaking changes
- [ ] Any documentation required has been added/updated. For changes to https://troubleshoot.sh/ create a PR [here](https://github.com/replicatedhq/troubleshoot.sh/pulls)

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

2024-12-02 17:10 UTC, banjoh commented
Thanks for your contribution. We'll review the PR

2024-12-02 17:49 UTC, banjoh requested changes
You took the right direction, but I'm concerned that a GPU device only considers Nvidia hardware. Users who have `gpu.intel.com/i915` or `gpu.intel.com/xe` for example, cannot use this analyser.

2024-12-02 17:52 UTC, banjoh commented
> You took the right direction, but I'm concerned that a GPU device only considers Nvidia hardware. Users who have `gpu.intel.com/i915` or `gpu.intel.com/xe` can use this analyser.

I don't yet have a clean suggestion that works, but I'd explore combining filters and outcomes.

2024-12-02 19:54 UTC, xavpaice commented
Internal tracking: https://app.shortcut.com/replicated/story/106618/in-cluster-collector-gpu-inventory

2024-12-02 19:59 UTC, xavpaice commented
> You took the right direction, but I'm concerned that a GPU device only considers Nvidia hardware. Users who have `gpu.intel.com/i915` or `gpu.intel.com/xe` for example, cannot use this analyser.

I think at this stage we can document the limitation and work with just Nvidia, expanding the scope in a future PR if there's demand.

2024-12-02 20:51 UTC, miguelvr commented
The more generic approach would be fetching by resource name. However it would have to be a function `resourceCapacity(nvidia.com/gpu, DecimalSI)`

This would cover any custom resource added by any device plugin.

I started on this, but I was having a hard time getting the regex to work as I wanted it to

2024-12-03 22:42 UTC, xavpaice commented
#1162 is related

2024-12-04 22:06 UTC, chris-sanders commented
@miguelvr we were reviewing this and issue #1162 from above and wanted to get your input on this approach.

https://docs.google.com/document/d/1thoEmuHpzf961cHHRreNjVB1rC_u8CVZYBCfxYNg8mY/edit?tab=t.0#heading=h.1q5hq5a3s115

I think that would be a bit more flexible to address the other open issue but want to confirm it would resolve your issue as well. I think it's what you're doing, but just a bit more flexible for the future. I'd like you to review that though and let us know what you think :)

2025-01-13 14:24 UTC, banjoh commented
@miguelvr I'll close this PR since this feature was implemented by https://github.com/replicatedhq/troubleshoot/pull/1708.

2025-01-13 14:24 UTC, closed without merging