feat(nodeResources): add GPU support
replicatedhq/troubleshoot pull request #1708
Opened 2024-12-19 05:26 UTC by DexterYan

## Description, Motivation and Context
- add `resourceName` and `resourceAllocatable`

## Checklist

- [ ] New and existing tests pass locally with introduced changes.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] The commit message(s) are informative and highlight any breaking changes
- [ ] Any documentation required has been added/updated. For changes to https://troubleshoot.sh/ create a PR [here](https://github.com/replicatedhq/troubleshoot.sh/pulls)

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

2024-12-20 18:35 UTC, banjoh requested changes

2024-12-20 18:35 UTC, banjoh commented on config/crds/troubleshoot.replicated.com_analyzers.yaml
> +                            resourceAllocatable:
`resourceCapacity` is missing

2024-12-20 18:35 UTC, banjoh commented on pkg/analyze/node_resources.go
> +		if filters.ResourceAllocatable != "" {
```yaml
- nodeResources:
   filters:
     resourceName: gpu.intel.com/i915
```

Using the spec above, if a node without `gpu.intel.com/i915` is present, this code will match it and count it in as a node with the intel GPU

We need to add a check here that checks if `node.Status.Allocatable["gpu.intel.com/i915"]` or `node.Status.Capacity["gpu.intel.com/i915"]` exist

2024-12-20 18:35 UTC, banjoh commented on pkg/analyze/node_resources.go
> +		if filters.ResourceAllocatable != "" {
Please add a unit test for this use case

2024-12-20 18:37 UTC, banjoh commented on pkg/analyze/node_resources.go
> +	}
```suggestion
	if filters != nil {
		resourceName = filters.ResourceName
	}
```

2024-12-20 18:40 UTC, banjoh commented on pkg/analyze/node_resources_test.go
> +		},
nit: For completeness, I'd add a `sum` unit test as well

2024-12-27 05:00 UTC, DexterYan commented
Thank you @banjoh, those tests have been added and code changed.

2024-12-31 13:13 UTC, banjoh submitted a review, later dismissed

2024-12-31 13:17 UTC, banjoh approved these changes

2025-01-03 02:11 UTC, merged