Added Namespace for Collection and Allows for tests to output to stdout
replicatedhq/troubleshoot pull request #91
Opened 2019-12-04 12:29 UTC by bearium

--namespace flag can now be passed into the support bundle and will now only collect resource information from specified namespace. if flag not specified default cluster wide resource collection is used.

--interactive=false now results in tests printing to stdout in go test format, allows for easier and quicker test inspection

go mod tidy was ran to clean up dependencies

2019-12-06 15:30 UTC, marccampbell commented
@bearium thanks for the contribution! This lgtm, and we will include it in our next release (Dec 9)

2019-12-06 23:55 UTC, divolgin requested changes
Thanks for the pull request.  There's just one small nit-picky thing.  Otherwise it looks good.

2019-12-06 23:55 UTC, divolgin commented on cmd/preflight/cli/stdout_results.go
> +		outputResult(analyzeResult)
`outputResult` should return the value that is currently stored in the global `failed` variable.   The the global variable should be removed.

2019-12-07 01:12 UTC, laverya commented on cmd/preflight/cli/stdout_results.go
> +var failed = false
Why the global variable and not something like having `outputResult` return the failure status?

2019-12-13 22:58 UTC, laverya approved these changes

2019-12-13 23:00 UTC, laverya commented
Thanks for the PR!

2019-12-13 23:01 UTC, merged