chore: Add CLI flags to enable CPU & memory profiling
replicatedhq/troubleshoot pull request #926
Opened 2022-12-22 15:50 UTC by banjoh

## Description, Motivation and Context

This PR add CLI flags that allow us to collect [CPU & memory profiling data](https://go.dev/doc/diagnostics#profiling). Here is how the use the flags

Run support bundle and with CPU & memory profile flags
```sh
./bin/support-bundle examples/support-bundle/sample-supportbundle.yaml --cpuprofile=cpu.prof --memprofile=mem.prof
```

Visualize using [pprof](https://github.com/google/pprof/blob/main/doc/README.md)
```sh
go tool pprof -http=":8000" cpu.prof

go tool pprof -http=":8001" mem.prof
```

## Checklist

- [ ] New and existing tests pass locally with introduced changes.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] The commit message(s) are informative and highlight any breaking changes
- [ ] Any documentation required has been added/updated. For changes to https://troubleshoot.sh/ create a PR [here](https://github.com/replicatedhq/troubleshoot.sh/pulls)

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

2022-12-22 15:56 UTC, banjoh commented on cmd/troubleshoot/cli/root.go
> -
Some clean up. This function is not in use.

2022-12-28 01:04 UTC, xavpaice requested changes
one print that I suspect was left in accidentally.

I have a query, not blocking: personally I find the nested returns in the cli package to be difficult to read.  I wonder if there's a longer but maybe more readable approach we could use?  Just a thought.

2022-12-28 01:04 UTC, xavpaice commented on cmd/analyze/cli/root.go
> +				fmt.Println(v.GetString("cpuprofile"))
was this left in deliberately?

2022-12-28 12:36 UTC, banjoh commented on cmd/analyze/cli/root.go
> +				fmt.Println(v.GetString("cpuprofile"))
This was left here accidentally.

Removed now

2022-12-28 12:49 UTC, banjoh commented
> I have a query, not blocking: personally I find the nested returns in the cli package to be difficult to read. I wonder if there's a longer but maybe more readable approach we could use? Just a thought.

I see your point. My first approach was inline with that, which included the boilerplate code required to setup and tear down the profiling environment. It worked but in my opinion, it added quite a bit of duplicate code that made it slightly harder to read code that implements actual functionality. I found it better to "hide away" these kind of non-functional features to make it easier  "see the forest from the trees" (if that makes sense :) ).

2022-12-28 14:01 UTC, banjoh commented
> One thing I did not explore was using `PreRun` & `PostRun` functions. I'll do that to see if the code becomes easier to understand.

I tried this approach which I think looks cleaner @xavpaice

2022-12-29 19:32 UTC, adamancini commented
@banjoh only nitpick I have is that when I go to use the new flags, if I don't specify a file path, a weird little shell bug happens:

```
 ✔  moira  /tmp/foo  ~/go/src/github.com/replicatedhq/troubleshoot/bin/support-bundle ~/go/src/github.com/replicatedhq/troubleshoot/examples/support-bundle/sample-supportbundle.yaml --cpuprofile --memprofile

 Collecting support bundle ⠦ cluster-info2022/12/29 14:30:22 An analyzer failed to run: open /var/folders/5t/4b638lkj34x81k36l95zw9ph0000gn/T/supportbundle182731251/support-bundle-2022-12-29T14_30_10/cluster-resources/ingress/default.json: no such file or directory
support-bundle-2022-12-29T14_30_10.tar.gz
 ✔  moira  /tmp/foo  ls -lha
total 264
-rw-r--r--  1 ada   wheel    13K Dec 29 14:30 --memprofile
drwxr-xr-x  4 ada   wheel   128B Dec 29 14:30 .
drwxrwxrwt  8 root  wheel   256B Dec 29 14:29 ..
-rw-r--r--  1 ada   wheel   114K Dec 29 14:30 support-bundle-2022-12-29T14_30_10.tar.gz
 ✔  moira  /tmp/foo  less --memprofile                                                                  
There is no memprofile option ("less --help" for help)
Missing filename ("less --help" for help)
 ✔  moira  /tmp/foo  less \-\-memprofile
There is no memprofile option ("less --help" for help)
Missing filename ("less --help" for help)
 ✔  moira  /tmp/foo  
```

it's like `--cpuprofile --memprofile` gets parsed as `--cpuprofile='--memprofile'` and this file gets written, but then the shell has a hard time interacting with it because it looks like a long flag

2022-12-30 13:25 UTC, banjoh commented
> @banjoh only nitpick I have is that when I go to use the new flags, if I don't specify a file path, a weird little shell bug happens:
> 
> ```
>  ✔  moira  /tmp/foo  ~/go/src/github.com/replicatedhq/troubleshoot/bin/support-bundle ~/go/src/github.com/replicatedhq/troubleshoot/examples/support-bundle/sample-supportbundle.yaml --cpuprofile --memprofile
> 
>  Collecting support bundle ⠦ cluster-info2022/12/29 14:30:22 An analyzer failed to run: open /var/folders/5t/4b638lkj34x81k36l95zw9ph0000gn/T/supportbundle182731251/support-bundle-2022-12-29T14_30_10/cluster-resources/ingress/default.json: no such file or directory
> support-bundle-2022-12-29T14_30_10.tar.gz
>  ✔  moira  /tmp/foo  ls -lha
> total 264
> -rw-r--r--  1 ada   wheel    13K Dec 29 14:30 --memprofile
> drwxr-xr-x  4 ada   wheel   128B Dec 29 14:30 .
> drwxrwxrwt  8 root  wheel   256B Dec 29 14:29 ..
> -rw-r--r--  1 ada   wheel   114K Dec 29 14:30 support-bundle-2022-12-29T14_30_10.tar.gz
>  ✔  moira  /tmp/foo  less --memprofile                                                                  
> There is no memprofile option ("less --help" for help)
> Missing filename ("less --help" for help)
>  ✔  moira  /tmp/foo  less \-\-memprofile
> There is no memprofile option ("less --help" for help)
> Missing filename ("less --help" for help)
>  ✔  moira  /tmp/foo  
> ```
> 
> it's like `--cpuprofile --memprofile` gets parsed as `--cpuprofile='--memprofile'` and this file gets written, but then the shell has a hard time interacting with it because it looks like a long flag
> 
> maybe if there's no `=/path/to/file` in the argument, we should default to $pwd that way the parser doesn't try to do something weird?

This is indeed a weird case. I'm not sure how to solve it. Any approach I'm taking has some form of compromise I don't like

- Checking if the value is a valid file path. That's a hard one cause any string can be a valid file path, including `--memprofile`
- Checking if the value passed in is not one of the cli flags. Hard as well, cause I can pass in `--cpuprofile=cpuprofile`
- Checking the equal sign is also not very intuitive cause `support-bundle --cpuprofile cpu.prof` ought to work according to how CLI applications behave.

I'm open to suggestions here

2022-12-30 21:06 UTC, xavpaice commented
Regards the CLI switches being unable to handle a default when no filename is specified, I believe that is a limitation of the CLI library we're using and not one which can be solved in this PR.  Other flags with a filename would have a default and always write to the default if the switch is not supplied, but for this application we don't want anything output if we do not supply the flag.  The alternative I can think of is we have default paths which can be overridden with the flags, but default also to not use the profiling unless we add a 3rd switch `--enable-profiling` or some such.

Alternately, we live with this limitation and make sure help text is clear on how to use these flags.

2023-01-03 12:42 UTC, banjoh commented
> Alternately, we live with this limitation and make sure help text is clear on how to use these flags.

Agreed. This is how [pflag library](https://github.com/spf13/pflag#command-line-flag-syntax) is designed to work. If it becomes an issue needing fixing, we can address it in another GH issue.

2023-01-03 17:22 UTC, divolgin commented on cmd/util/profilers.go
> +		pprof.StopCPUProfile()
This will never happen if there is an error writing memory profile.  Ideally these two should be independent.

2023-01-03 17:22 UTC, divolgin approved these changes, later dismissed

2023-01-03 18:23 UTC, diamonwiggins approved these changes
lgtm

2023-01-03 18:56 UTC, xavpaice approved these changes

2023-01-04 11:56 UTC, merged